name: Bug Report
description: An unexpected problem or behavior in the system
type: Bug
body:
  - type: textarea
    id: observed
    attributes:
      label: Observed Behaviour
      description: What happened ?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: What was expected?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: |
        How one can reproduce the bug?
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
  - type: textarea
    id: fixes
    attributes:
      label: Possible fixes
      description: Enter any ideas that you may have for potential solutions
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
