name: Documentation Task
description: Propose updates or additions to project documentation.
type: Documentation
body:
  - type: markdown
    attributes:
      value: |
        ## Documentation Task

        Thank you for helping improve our documentation! Please provide as much detail as possible to help us address this documentation need efficiently.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation does this issue affect?
      options:
        - README or Getting Started
        - API Reference
        - Usage Example
        - Troubleshooting
        - Code Comments
        - Other

  - type: textarea
    id: current
    attributes:
      label: Current or Missing Documentation
      description: What currently exists, or what is missing or outdated?

  - type: textarea
    id: expected
    attributes:
      label: Requested Change or Addition
      description: What should be updated or added? List details, sections, or examples needed.

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any related resources, links, or screenshots to clarify the request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched for related documentation issues and found none.
          required: true
